package:
  name: ot2rec
  version: 0.2.0

source:
  path: ..

build:
  number: 0
  entry_points:
      - o2r.new=Ot2Rec.main:new_proj
      - o2r.mc.new=Ot2Rec.motioncorr:create_yaml
      - o2r.mc.run=Ot2Rec.motioncorr:run
      - o2r.ctffind.new=Ot2Rec.ctffind:create_yaml
      - o2r.ctffind.run=Ot2Rec.ctffind:run
      - o2r.ctfsim.run=Ot2Rec.ctfsim:run
      - o2r.imod.align.new=Ot2Rec.align:create_yaml
      - o2r.imod.align.stacks=Ot2Rec.align:imod_create_stacks
      - o2r.imod.align.run=Ot2Rec.align:imod_standard_align
      - o2r.imod.align.new_ext=Ot2Rec.align:create_yaml_stacked
      - o2r.imod.align.run_ext=Ot2Rec.align:imod_align_ext
      - o2r.imod.align.stats=Ot2Rec.align:get_align_stats
      - o2r.imod.recon.new=Ot2Rec.recon:create_yaml
      - o2r.imod.recon.run=Ot2Rec.recon:run
      - o2r.savu.recon.new=Ot2Rec.savurecon:create_yaml
      - o2r.savu.recon.run=Ot2Rec.savurecon:run
      - o2r.aretomo.new=Ot2Rec.aretomo:create_yaml
      - o2r.aretomo.run=Ot2Rec.aretomo:run
      - o2r.deconv.run=Ot2Rec.rlf_deconv:run
      - o2r.cleanup=Ot2Rec.main:cleanup
      - o2r.runall=Ot2Rec.main:run_all
	    
requirements:
  host:
    - python
    - setuptools
    - pip
    
  run: 
    - python
    - tqdm
    - pandas
    - pyyaml
    - multiprocess
    - icecream
    - beautifultable
    - scikit-image
    - mrcfile
    - tifffile
    - redlionfish
    - magicgui
    - pyqt

about:
  home: https://github.com/RosalindFranklinInstitute/Ot2Rec
  summary: wrapper software for Electron Microscopy pipelines
  license: Apache-2.0